import { GRID } from '../game/GameConfig.js';

export class CombatSystem {
  constructor(physicsSystem) {
    this.physicsSystem = physicsSystem;
    this.projectiles = [];
    this.enemyProjectiles = [];
    this.meleeAttacks = [];
    this.enemyMeleeAttacks = [];
    this.pendingMeleeAttacks = []; // Attacks waiting to spawn
    this.damageNumbers = [];
    this.objectDestroyEvents = []; // { obj, effect } collected each frame
    this.impactEffects = [];       // { x, y, onHit, color } — elemental hit sparks
    this.newSteamClouds = [];      // { x, y, radius, timer } — generated by fire+water
    this.stuckArrows = [];         // { char, position, stuckTo, offset, color, isBurning }
    this.polymorphEvents = [];     // { enemy, outcome } — polymorph transformations to process
    this.aoeEffects = [];          // { type, x, y, radius, timer, color } — AOE visual effects (wand explosions)
  }

  update(deltaTime, player, enemies, backgroundObjects = [], noiseSource = null, room = null) {
    // Red warrior damage roll: hits and knocks back enemies, smashes background objects
    this.updateRollDamage(player, enemies, backgroundObjects);

    // Update pending melee attacks (for delayed spawning like flail sweep)
    for (let i = this.pendingMeleeAttacks.length - 1; i >= 0; i--) {
      const pending = this.pendingMeleeAttacks[i];
      pending.delay -= deltaTime;

      if (pending.delay <= 0) {
        // Recalculate position from owner's current location so moving
        // multi-hit weapons (flail, arc, sweep, etc.) track the player
        const spawnPosition = (pending.relX !== undefined && pending.owner)
          ? { x: pending.owner.position.x + pending.relX, y: pending.owner.position.y + pending.relY }
          : pending.position;
        this.meleeAttacks.push({
          ...pending,
          position: spawnPosition,
          hasHit: false
        });
        this.pendingMeleeAttacks.splice(i, 1);
      }
    }

    // Update damage numbers
    for (let i = this.damageNumbers.length - 1; i >= 0; i--) {
      const dmgNum = this.damageNumbers[i];

      dmgNum.timer += deltaTime;
      dmgNum.y -= dmgNum.riseSpeed * deltaTime;
      dmgNum.alpha = Math.max(0, 1 - (dmgNum.timer / dmgNum.duration));

      if (dmgNum.timer >= dmgNum.duration) {
        this.damageNumbers.splice(i, 1);
      }
    }

    // Update wand proximity failure indicators
    if (!this.wandProximityFailures) {
      this.wandProximityFailures = [];
    }
    for (let i = this.wandProximityFailures.length - 1; i >= 0; i--) {
      const failure = this.wandProximityFailures[i];
      failure.timer -= deltaTime;

      if (failure.timer <= 0) {
        this.wandProximityFailures.splice(i, 1);
      }
    }

    // Update AOE visual effects
    for (let i = this.aoeEffects.length - 1; i >= 0; i--) {
      const effect = this.aoeEffects[i];
      effect.timer -= deltaTime;

      if (effect.timer <= 0) {
        this.aoeEffects.splice(i, 1);
      }
    }

    // Update projectiles
    for (let i = this.projectiles.length - 1; i >= 0; i--) {
      const proj = this.projectiles[i];

      // Homing behavior
      if (proj.homing && enemies.length > 0) {
        let nearestEnemy = null;
        let nearestDist = Infinity;

        for (const enemy of enemies) {
          const dx = enemy.position.x - proj.position.x;
          const dy = enemy.position.y - proj.position.y;
          const dist = Math.sqrt(dx * dx + dy * dy);

          if (dist < nearestDist) {
            nearestEnemy = enemy;
            nearestDist = dist;
          }
        }

        if (nearestEnemy) {
          const dx = nearestEnemy.position.x - proj.position.x;
          const dy = nearestEnemy.position.y - proj.position.y;
          const angle = Math.atan2(dy, dx);
          const speed = Math.sqrt(proj.velocity.vx ** 2 + proj.velocity.vy ** 2);

          // Gradually turn towards target
          const turnRate = 3.0 * deltaTime;
          const currentAngle = Math.atan2(proj.velocity.vy, proj.velocity.vx);
          let angleDiff = angle - currentAngle;

          // Normalize angle difference
          while (angleDiff > Math.PI) angleDiff -= Math.PI * 2;
          while (angleDiff < -Math.PI) angleDiff += Math.PI * 2;

          const newAngle = currentAngle + angleDiff * turnRate;
          proj.velocity.vx = Math.cos(newAngle) * speed;
          proj.velocity.vy = Math.sin(newAngle) * speed;
        }
      }

      // Apply deceleration to arrows (maintains speed initially, hard falloff at end)
      if (proj.type === 'arrow') {
        // Store initial speed on first frame
        if (!proj.initialSpeed) {
          proj.initialSpeed = Math.sqrt(proj.velocity.vx ** 2 + proj.velocity.vy ** 2);
        }

        const speed = Math.sqrt(proj.velocity.vx ** 2 + proj.velocity.vy ** 2);

        if (speed > 0) {
          // Inverse decay: deceleration increases as arrow slows (hard falloff near end)
          const speedRatio = speed / proj.initialSpeed; // 1.0 at start, approaches 0 at end
          const decayStrength = Math.pow(1.0 - speedRatio, 2); // Gets stronger as arrow slows
          const baseDecay = 0.98; // Minimal decay at full speed
          const decayRate = baseDecay - (decayStrength * 0.15); // Max decay of 0.83 when nearly stopped

          const newSpeed = speed * Math.pow(decayRate, deltaTime * 60);

          // Apply deceleration along the velocity vector
          const scale = newSpeed / speed;
          proj.velocity.vx *= scale;
          proj.velocity.vy *= scale;

          // Arrow has stopped - create stuck arrow on ground
          if (newSpeed < 30) {
            this.stuckArrows.push({
              char: proj.char,
              position: { x: proj.position.x, y: proj.position.y },
              stuckTo: null, // Not stuck to anything, just on the ground
              offset: { x: 0, y: 0 },
              color: proj.color,
              isBurning: proj.onHit === 'burn',
              burnParticleTimer: 0
            });
            this.projectiles.splice(i, 1);
            continue;
          }
        }
      }

      // Move projectile
      proj.position.x += proj.velocity.vx * deltaTime;
      proj.position.y += proj.velocity.vy * deltaTime;

      // Update plane if in tunnel room
      if (room && room.tunnel && proj.plane !== undefined) {
        this.updateProjectilePlane(proj, room.tunnel);
      }

      // Check collision with background objects
      let bgObjectHit = false;
      for (const obj of backgroundObjects) {
        if (obj.destroyed || obj.isRecipeSign) continue; // Skip destroyed and recipe signs

        if (this.checkProjectileCollisionWithObject(proj, obj)) {
          const result = obj.handleBulletCollision(proj);

          // Handle bullet behavior
          if (result.bulletBehavior === 'slow') {
            const mult = result.speedMultiplier !== undefined ? result.speedMultiplier : 0.5;
            if (result.speedMultiplier !== undefined) {
              // One-time slow per object (e.g. arrows through grass): only apply on first contact
              if (!proj.slowedByObjects) proj.slowedByObjects = new Set();
              if (!proj.slowedByObjects.has(obj)) {
                proj.slowedByObjects.add(obj);
                // Speed floor: grass clusters can't slow an arrow below 80% of its launch speed
                const currentSpeed = Math.hypot(proj.velocity.vx, proj.velocity.vy);
                const floorSpeed = (proj.initialSpeed || currentSpeed) * 0.80;
                if (currentSpeed * mult >= floorSpeed) {
                  proj.velocity.vx *= mult;
                  proj.velocity.vy *= mult;
                } else if (currentSpeed > floorSpeed) {
                  // Clamp to floor without overshooting
                  const scale = floorSpeed / currentSpeed;
                  proj.velocity.vx *= scale;
                  proj.velocity.vy *= scale;
                }
              }
            } else {
              proj.velocity.vx *= mult;
              proj.velocity.vy *= mult;
            }
          } else if (result.bulletBehavior === 'reflectBullet' || result.effect === 'reflectBullet') {
            // Reflect bullet
            this.reflectBullet(proj, obj);
          }

          // Collect drop effects from destroyed objects
          if (result.effect && result.effect !== 'reflectBullet') {
            this.objectDestroyEvents.push({ obj, effect: result.effect });
          }

          // Chaff VFX when bullets or arrows hit grass (tall or cut) — 5% chance
          if ((proj.type === 'bullet' || proj.type === 'arrow') && (obj.char === '|' || obj.char === ',') && Math.random() < 0.05) {
            this.impactEffects.push({
              x: obj.position.x,
              y: obj.position.y,
              effect: 'chaff',
              color: '#667755'
            });
          }

          // Electric conduction (only for electric weapons)
          if (obj.isConductive() && proj.onHit === 'stun' && proj.electric) {
            const electricResult = this.conductElectricity(obj, proj.damage, enemies, player);
            if (electricResult?.playerDead) {
              return { playerDead: true };
            }
          }

          // Fire interactions — also spread to adjacent objects if this one is destroyed
          if (proj.onHit === 'burn' && obj.isFlammable()) {
            const ignited = obj.ignite(5.0);
            if (ignited) {
              this.createDamageNumber('!', obj.position.x, obj.position.y, '#ff4400');
            }
            if (obj.destroyAfterAnimation) {
              // Source object is dying; spread fire outward immediately
              for (const other of backgroundObjects) {
                if (other === obj || other.destroyed || !other.isFlammable()) continue;
                const dx = other.position.x - obj.position.x;
                const dy = other.position.y - obj.position.y;
                if (dx * dx + dy * dy < 48 * 48) other.ignite(5.0);
              }
            }
          }
          // Emit impact effect for elemental projectiles (skip water — it has its own feedback)
          if (proj.onHit && !(obj.isWater && obj.isWater())) {
            this.impactEffects.push({ x: obj.position.x, y: obj.position.y, onHit: proj.onHit, color: proj.color });
          }

          // Water state transitions from projectiles
          if (obj.isWater && obj.isWater()) {
            if (proj.onHit === 'freeze') {
              obj.setWaterState('frozen', Infinity); // Stays frozen until thawed by fire
              this.createDamageNumber('❄', obj.position.x, obj.position.y, '#aaddff');
            } else if (proj.onHit === 'poison') {
              obj.setWaterState('poisoned', 8.0);
              this.createDamageNumber('☠', obj.position.x, obj.position.y, '#44bb44');
            } else if (proj.onHit === 'stun' && proj.electric) {
              obj.setWaterState('electrified', 5.0);
              this.createDamageNumber('⚡', obj.position.x, obj.position.y, '#cccc00');
            } else if (proj.onHit === 'burn') {
              if (obj.getWaterState() === 'frozen') {
                obj.setWaterState('normal', 0); // Melt ice
                this.createDamageNumber('~', obj.position.x, obj.position.y, '#3366ff');
              } else {
                // Fire hits liquid water → steam cloud
                this.newSteamClouds.push({
                  x: obj.position.x + GRID.CELL_SIZE / 2,
                  y: obj.position.y + GRID.CELL_SIZE / 2,
                  radius: GRID.CELL_SIZE * 3,
                  timer: 7.0
                });
                this.createDamageNumber('=', obj.position.x, obj.position.y, '#aaaaaa');
              }
            }
          }

          // Destroy bullet if needed
          if (result.shouldDestroyBullet) {
            bgObjectHit = true;

            // Create stuck arrow if this is an arrow hitting any background object
            if (proj.type === 'arrow') {
              this.stuckArrows.push({
                char: proj.char,
                position: { x: proj.position.x, y: proj.position.y },
                stuckTo: obj,
                offset: {
                  x: proj.position.x - obj.position.x,
                  y: proj.position.y - obj.position.y
                },
                color: proj.color,
                isBurning: proj.onHit === 'burn',
                burnParticleTimer: 0
              });
            }
            break;
          }
        }
      }

      if (bgObjectHit) {
        this.projectiles.splice(i, 1);
        continue;
      }

      // Ricochet behavior
      if (proj.ricochet) {
        const bounced = this.checkRicochet(proj);
        if (bounced) {
          proj.ricochetCount = (proj.ricochetCount || 0) + 1;
          if (proj.ricochetCount >= (proj.maxRicochets || 3)) {
            this.projectiles.splice(i, 1);
            continue;
          }
        }
      }

      // Check bounds
      if (this.isOutOfBounds(proj)) {
        this.projectiles.splice(i, 1);
        continue;
      }

      // Check collision with enemies
      let hit = false;
      for (const enemy of enemies) {
        // Skip if projectile and enemy are in different planes
        if (proj.plane !== undefined && enemy.plane !== undefined && proj.plane !== enemy.plane) {
          continue;
        }

        if (this.checkProjectileCollision(proj, enemy)) {
          // Special handling for transmutation bolt - polymorph enemy
          if (proj.type === 'transmutation_bolt') {
            // Store polymorph event to process after projectile loop
            this.polymorphEvents.push({
              enemy: enemy,
              position: enemy.position
            });
            hit = true;
            break;
          }

          // Calculate arrow speed falloff (damage decreases as arrow slows down)
          let speedMultiplier = 1.0;
          if (proj.type === 'arrow' && proj.initialSpeed) {
            const currentSpeed = Math.sqrt(proj.velocity.vx ** 2 + proj.velocity.vy ** 2);
            speedMultiplier = currentSpeed / proj.initialSpeed; // 1.0 at full speed, approaches 0 as arrow slows
          }

          // Apply elemental affinity modifier and speed falloff
          const elementalMod = enemy.getElementalModifier(proj.onHit);
          let adjustedDamage = Math.ceil(proj.damage * elementalMod * speedMultiplier);
          // Green Ranger flat modifier applied after multipliers so it isn't scaled by speed falloff
          if (proj.owner && proj.owner.characterType === 'green') {
            const enemyUndetected = enemy.detectionIndicatorTimer <= 0;
            const greenBonus = enemyUndetected ? proj.owner.greenIdleDamageBonus : -proj.owner.greenCombatDamagePenalty;
            adjustedDamage = Math.max(1, adjustedDamage + greenBonus);
          }

          // Handle immunity
          if (elementalMod === 0.0) {
            this.createDamageNumber('IMMUNE', enemy.position.x, enemy.position.y, '#cccccc');
            if (!proj.pierce) {
              hit = true;
              break;
            }
            continue;
          }

          const damaged = enemy.takeDamage(adjustedDamage, proj.attackId);
          if (damaged !== false) {
            // Show damage number with color based on affinity
            const damageColor = elementalMod < 1.0 ? '#888888' :   // Resisted
                               elementalMod > 1.0 ? '#ffff00' :    // Weakness
                               enemy.color;                        // Normal
            this.createDamageNumber(adjustedDamage, enemy.position.x, enemy.position.y, damageColor);

            // Show weakness indicator
            if (elementalMod > 1.0) {
              this.createDamageNumber('!', enemy.position.x, enemy.position.y - 12, '#ff4400');
            }

            // Apply status effects with affinity-modified duration
            if (proj.onHit && enemy.shouldApplyStatusEffect(proj.onHit)) {
              const baseDuration = 3.0;
              const modifiedDuration = baseDuration * elementalMod;

              if (proj.onHit === 'freeze') {
                // Freeze escalation: second ice hit while frozen → stun (freeze continues)
                if (enemy.statusEffects.freeze && enemy.statusEffects.freeze.active) {
                  enemy.applyStatusEffect('stun', 2.5 * elementalMod);
                } else {
                  enemy.applyStatusEffect('freeze', 8.0 * elementalMod);
                }
              } else {
                enemy.applyStatusEffect(proj.onHit, modifiedDuration);
              }
              // Emit impact effect for visual feedback
              this.impactEffects.push({ x: enemy.position.x, y: enemy.position.y, onHit: proj.onHit, color: proj.color });
            } else if (proj.onHit && !enemy.shouldApplyStatusEffect(proj.onHit)) {
              this.createDamageNumber('RESIST', enemy.position.x, enemy.position.y - 12, '#888888');
            }

            // Apply knockback
            if (proj.knockback) {
              this.applyKnockback(enemy, proj);
            }

            // Apply lifesteal to player
            if (proj.lifesteal && proj.owner === 'player') {
              proj.owner.hp = Math.min(proj.owner.hp + proj.damage * proj.lifesteal, proj.owner.maxHp);
            }

            // Chain lightning effect
            if (proj.chain && proj.chainCount > 0) {
              this.createChainLightning(proj, enemy, enemies);
            }

            // Explosion effect
            if (proj.explode) {
              this.createExplosion(proj.position.x, proj.position.y, proj.explodeRadius || 30, proj.damage, enemies, backgroundObjects);
            }
          }

          // Pierce projectiles don't get removed
          if (!proj.pierce) {
            hit = true;

            // Create stuck arrow if this is an arrow
            if (proj.type === 'arrow') {
              this.stuckArrows.push({
                char: proj.char,
                position: { x: proj.position.x, y: proj.position.y },
                stuckTo: enemy,
                offset: {
                  x: proj.position.x - enemy.position.x,
                  y: proj.position.y - enemy.position.y
                },
                color: proj.color,
                isBurning: proj.onHit === 'burn',
                burnParticleTimer: 0
              });
            }
          }

          // Split projectiles
          if (proj.split && !proj.hasSplit) {
            this.createSplitProjectiles(proj);
            proj.hasSplit = true;
          }

          if (!proj.pierce) break;
        }
      }

      if (hit) {
        this.projectiles.splice(i, 1);
      }
    }

    // Update melee attacks
    for (let i = this.meleeAttacks.length - 1; i >= 0; i--) {
      const attack = this.meleeAttacks[i];

      attack.duration -= deltaTime;

      if (attack.duration <= 0) {
        this.meleeAttacks.splice(i, 1);
        continue;
      }

      // Check collision with background objects (only on first frame)
      if (!attack.hasHitObject) {
        for (const obj of backgroundObjects) {
          if (obj.destroyed || obj.isRecipeSign) continue; // Skip destroyed and recipe signs

          if (this.checkMeleeCollisionWithObject(attack, obj)) {
            // Glittering rocks require a pickaxe — other weapons bounce off
            if (obj.data?.glitteringRock) {
              if (!attack.isPickaxe) {
                this.createDamageNumber('!', obj.position.x, obj.position.y, '#aaaaaa');
                continue;
              }
              const result = obj.takeDamage(attack.damage);
              if (result.destroyed && result.effect) {
                this.objectDestroyEvents.push({ obj, effect: result.effect });
              }
              attack.hasHitObject = true;
              continue;
            }

            // Blunt weapons can't damage objects, but still rustle grass
            if (!attack.isBlunt) {
              const smashDamage = attack.canSmash ? attack.damage * 2 : attack.damage;
              const result = obj.takeDamage(smashDamage, attack.isBlade);

              if (result.destroyed && result.effect) {
                this.objectDestroyEvents.push({ obj, effect: result.effect });
              }

              // Fire weapons ignite flammable objects — spread outward if object is destroyed
              if (attack.onHit === 'burn' && obj.isFlammable()) {
                const ignited = obj.ignite(5.0);
                if (ignited) {
                  this.createDamageNumber('!', obj.position.x, obj.position.y, '#ff4400');
                }
                if (result.destroyed) {
                  for (const other of backgroundObjects) {
                    if (other === obj || other.destroyed || !other.isFlammable()) continue;
                    const dx = other.position.x - obj.position.x;
                    const dy = other.position.y - obj.position.y;
                    if (dx * dx + dy * dy < 48 * 48) other.ignite(5.0);
                  }
                }
              }
              // Emit impact effect for elemental melee (skip water — it has its own feedback)
              if (attack.onHit && !(obj.isWater && obj.isWater())) {
                this.impactEffects.push({ x: obj.position.x, y: obj.position.y, onHit: attack.onHit, color: attack.color });
              }

              // Electric weapons conduct through conductive objects
              if (attack.onHit === 'stun' && attack.electric && obj.isConductive()) {
                this.conductElectricity(obj, attack.damage, enemies, player);
              }

              // Water state transitions from melee
              if (obj.isWater && obj.isWater()) {
                if (attack.onHit === 'freeze') {
                  obj.setWaterState('frozen', Infinity); // Stays frozen until thawed by fire
                  this.createDamageNumber('❄', obj.position.x, obj.position.y, '#aaddff');
                } else if (attack.onHit === 'poison') {
                  obj.setWaterState('poisoned', 8.0);
                  this.createDamageNumber('☠', obj.position.x, obj.position.y, '#44bb44');
                } else if (attack.onHit === 'stun' && attack.electric) {
                  obj.setWaterState('electrified', 5.0);
                  this.createDamageNumber('⚡', obj.position.x, obj.position.y, '#cccc00');
                } else if (attack.onHit === 'burn') {
                  if (obj.getWaterState() === 'frozen') {
                    obj.setWaterState('normal', 0); // Melt ice
                    this.createDamageNumber('~', obj.position.x, obj.position.y, '#3366ff');
                  } else {
                    // Fire hits liquid water → steam cloud
                    this.newSteamClouds.push({
                      x: obj.position.x + GRID.CELL_SIZE / 2,
                      y: obj.position.y + GRID.CELL_SIZE / 2,
                      radius: GRID.CELL_SIZE * 3,
                      timer: 7.0
                    });
                    this.createDamageNumber('=', obj.position.x, obj.position.y, '#aaaaaa');
                  }
                }
              }
            }

            // Chaff VFX when melee hits grass (all weapons including blunt) — 5% chance
            if ((obj.char === '|' || obj.char === ',') && Math.random() < 0.05) {
              this.impactEffects.push({
                x: obj.position.x,
                y: obj.position.y,
                effect: 'chaff',
                color: '#667755'
              });
            }
          }
        }
        attack.hasHitObject = true;
      }

      // Check collision with enemies (only on first frame)
      if (!attack.hasHit) {
        for (const enemy of enemies) {
          // Skip if attack and enemy are in different planes
          if (attack.shooterPlane !== undefined && enemy.plane !== undefined && attack.shooterPlane !== enemy.plane) {
            continue;
          }

          if (this.checkMeleeCollision(attack, enemy)) {
            const isWet = enemy.isWet && enemy.isWet();

            // Apply elemental affinity modifier
            const elementalMod = enemy.getElementalModifier(attack.onHit);

            // Green Ranger stealth modifier: bonus when enemy hasn't detected the player
            let totalDamage = attack.damage;
            if (attack.owner && attack.owner.characterType === 'green') {
              const enemyUndetected = enemy.detectionIndicatorTimer <= 0;
              const greenBonus = enemyUndetected ? attack.owner.greenIdleDamageBonus : -attack.owner.greenCombatDamagePenalty;
              totalDamage = Math.max(1, totalDamage + greenBonus);
            }

            // Wet enemies take bonus damage from electric and ice attacks
            const isFrozen = enemy.statusEffects.freeze && enemy.statusEffects.freeze.active;
            let statusDuration = 3.0;
            if (isWet && attack.onHit === 'stun') {
              totalDamage *= 2;      // Double damage from electricity on wet enemies
              statusDuration = 3.5;  // Extended stun
            } else if (isWet && attack.onHit === 'freeze') {
              totalDamage += Math.ceil(attack.damage * 0.5); // +50% from ice on wet enemies
              statusDuration = 5.0;  // Extended freeze
            }

            // Blunt weapons deal 2.5x damage to frozen enemies
            if (isFrozen && attack.weaponSubtype === 'hammer') {
              totalDamage = Math.ceil(totalDamage * 2.5);
            }

            // Apply elemental modifier to final damage
            totalDamage = Math.ceil(totalDamage * elementalMod);

            // Handle immunity
            if (elementalMod === 0.0) {
              this.createDamageNumber('IMMUNE', enemy.position.x, enemy.position.y, '#cccccc');
              continue;
            }

            const damaged = enemy.takeDamage(totalDamage);
            if (damaged !== false) {
              // Show damage number with color based on affinity
              const damageColor = elementalMod < 1.0 ? '#888888' :   // Resisted
                                 elementalMod > 1.0 ? '#ffff00' :    // Weakness
                                 enemy.color;                        // Normal
              this.createDamageNumber(totalDamage, enemy.position.x, enemy.position.y, damageColor);

              // Show weakness indicator
              if (elementalMod > 1.0) {
                this.createDamageNumber('!', enemy.position.x, enemy.position.y - 12, '#ff4400');
              }

              // Apply status effects with affinity-modified duration
              if (attack.onHit && enemy.shouldApplyStatusEffect(attack.onHit)) {
                const modifiedDuration = statusDuration * elementalMod;

                if (attack.onHit === 'freeze') {
                  // Freeze escalation: second ice hit while frozen → stun (freeze continues)
                  if (isFrozen) {
                    enemy.applyStatusEffect('stun', 2.5 * elementalMod);
                  } else {
                    enemy.applyStatusEffect('freeze', 8.0 * elementalMod);
                  }
                } else {
                  enemy.applyStatusEffect(attack.onHit, modifiedDuration);
                }
                // Emit impact effect for visual feedback
                this.impactEffects.push({ x: enemy.position.x, y: enemy.position.y, onHit: attack.onHit, color: attack.color });
              } else if (attack.onHit && !enemy.shouldApplyStatusEffect(attack.onHit)) {
                this.createDamageNumber('RESIST', enemy.position.x, enemy.position.y - 12, '#888888');
              }

              // Show electric indicator for wet-boosted hits
              if (isWet && attack.onHit === 'stun') {
                this.createDamageNumber('⚡', enemy.position.x, enemy.position.y - 12, '#ffff00');
              }

              // Show blunt-on-frozen bonus indicator
              if (isFrozen && attack.weaponSubtype === 'hammer') {
                this.createDamageNumber('*', enemy.position.x, enemy.position.y - 12, '#00ddff');
              }

              // Apply knockback
              if (attack.knockback) {
                this.applyKnockback(enemy, attack);
              }

              // Apply lifesteal
              if (attack.lifesteal && attack.owner) {
                attack.owner.hp = Math.min(attack.owner.hp + attack.damage * attack.lifesteal, attack.owner.maxHp);
              }

              // Chain lightning effect
              if (attack.chain) {
                this.createChainLightning(attack, enemy, enemies);
              }

              // Explosion effect
              if (attack.explode) {
                this.createExplosion(attack.position.x, attack.position.y, attack.explodeRadius || 40, attack.damage, enemies, backgroundObjects);
              }
            }
          }
        }
        attack.hasHit = true;
      }
    }

    // Update enemy projectiles
    for (let i = this.enemyProjectiles.length - 1; i >= 0; i--) {
      const proj = this.enemyProjectiles[i];

      // Move projectile
      proj.position.x += proj.velocity.vx * deltaTime;
      proj.position.y += proj.velocity.vy * deltaTime;

      // Update plane if in tunnel room
      if (room && room.tunnel && proj.plane !== undefined) {
        this.updateProjectilePlane(proj, room.tunnel);
      }

      // Check bounds
      if (this.isOutOfBounds(proj)) {
        this.enemyProjectiles.splice(i, 1);
        continue;
      }


      // Skip if projectile and player are in different planes
      if (proj.plane !== undefined && player.plane !== undefined && proj.plane !== player.plane) {
        continue;
      }

      // Check collision with player
      if (this.checkProjectileCollisionWithPlayer(proj, player)) {
        if (player.tryShieldBlock && player.tryShieldBlock(true)) {
          // Shield absorbed the bullet
          this.createDamageNumber('*', player.position.x, player.position.y, '#aaddff');
        } else {
          // Build damage source object
          const damageSource = {
            isBullet: true,
            element: proj.onHit,
            attacker: proj.owner
          };
          const result = player.takeDamage(proj.damage, damageSource);

          // Handle special results
          if (result.dodged) {
            this.createDamageNumber('DODGE', player.position.x, player.position.y, '#ffff00');
          } else if (result.blocked) {
            this.createDamageNumber('BLOCK', player.position.x, player.position.y, '#aaaaaa');
          } else if (result.immune) {
            this.createDamageNumber('IMMUNE', player.position.x, player.position.y, '#00ffff');
          } else if (result !== false) {
            this.createDamageNumber(proj.damage, player.position.x, player.position.y, player.color);

            // Handle reflection
            if (result.reflect && result.attacker) {
              result.attacker.takeDamage(result.reflect);
              this.createDamageNumber(result.reflect, result.attacker.position.x, result.attacker.position.y, '#ff8800');
            }
          }

          if (result === true) {
            this.enemyProjectiles.splice(i, 1);
            return { playerDead: true };
          }

          // Create stuck arrow if this is an arrow (not a bullet/magic)
          if (proj.type === 'arrow') {
            this.stuckArrows.push({
              char: proj.char,
              position: { x: proj.position.x, y: proj.position.y },
              stuckTo: player,
              offset: {
                x: proj.position.x - player.position.x,
                y: proj.position.y - player.position.y
              },
              color: proj.color,
              isBurning: proj.onHit === 'burn',
              burnParticleTimer: 0
            });
          }
        }
        this.enemyProjectiles.splice(i, 1);
      }
    }

    // Update enemy melee attacks
    for (let i = this.enemyMeleeAttacks.length - 1; i >= 0; i--) {
      const attack = this.enemyMeleeAttacks[i];

      attack.duration -= deltaTime;

      // Update windup alpha (blink effect via transparency)
      if (attack.windupPhase && attack.windupDuration !== undefined) {
        attack.windupElapsed += deltaTime;
        const progress = attack.windupElapsed / attack.windupDuration;

        // Alpha pattern: 0%=1.0, 25%=0.25, 50%=1.0, 75%=0.25, 100%=white
        if (progress < 0.25) {
          attack.alpha = 1.0; // Fully visible
        } else if (progress < 0.5) {
          attack.alpha = 0.25; // Dimmed (first dip)
        } else if (progress < 0.75) {
          attack.alpha = 1.0; // Fully visible
        } else {
          attack.alpha = 0.25; // Dimmed (second dip)
        }
      }

      // Update flash timer
      if (attack.flashTimer !== undefined && attack.flashTimer > 0) {
        attack.flashTimer -= deltaTime;
        if (attack.flashTimer <= 0) {
          attack.flashWhite = false;
        }
      }

      if (attack.duration <= 0) {
        this.enemyMeleeAttacks.splice(i, 1);
        continue;
      }

      // Check collision with player or charmed target (only on first frame, not during windup)
      if (!attack.hasHit && !attack.windupPhase) {

        if (attack.isCharmedAttack && attack.charmedTarget && attack.charmedTarget !== player) {
          // Charmed attack hits the charmed target enemy
          if (this.checkMeleeCollision(attack, attack.charmedTarget)) {
            attack.charmedTarget.takeDamage(attack.damage);
            this.createDamageNumber(attack.damage, attack.charmedTarget.position.x, attack.charmedTarget.position.y, '#ff44ff');
          }
        } else {
          // Skip if attack and player are in different planes
          if (attack.shooterPlane !== undefined && player.plane !== undefined && attack.shooterPlane !== player.plane) {
            attack.hasHit = true; // Mark as processed so it doesn't linger
            continue;
          }

          // Normal attack (or charmed fallback targeting player)
          if (this.checkMeleeCollisionWithPlayer(attack, player)) {
            if (player.tryShieldBlock && player.tryShieldBlock(false)) {
              // Tower Shield absorbed the melee hit
              this.createDamageNumber('*', player.position.x, player.position.y, '#8888ff');
            } else {
              // Build damage source object
              const damageSource = {
                isBullet: false,
                element: attack.onHit,
                attacker: attack.owner
              };
              const result = player.takeDamage(attack.damage, damageSource);

              // Handle special results
              if (result.dodged) {
                this.createDamageNumber('DODGE', player.position.x, player.position.y, '#ffff00');
              } else if (result.blocked) {
                this.createDamageNumber('BLOCK', player.position.x, player.position.y, '#aaaaaa');
              } else if (result.immune) {
                this.createDamageNumber('IMMUNE', player.position.x, player.position.y, '#00ffff');
              } else if (result !== false) {
                this.createDamageNumber(attack.damage, player.position.x, player.position.y, player.color);

                // Apply knockback to player
                if (attack.knockback) {
                  const dx = player.position.x - attack.position.x;
                  const dy = player.position.y - attack.position.y;
                  const distance = Math.sqrt(dx * dx + dy * dy) || 1;
                  const knockbackForce = attack.knockback || 200;
                  player.velocity.vx = (dx / distance) * knockbackForce;
                  player.velocity.vy = (dy / distance) * knockbackForce;
                }

                // Handle reflection
                if (result.reflect && result.attacker) {
                  result.attacker.takeDamage(result.reflect);
                  this.createDamageNumber(result.reflect, result.attacker.position.x, result.attacker.position.y, '#ff8800');
                }
              }

              if (result === true) {
                return { playerDead: true };
              }
            }
          }
        }
        attack.hasHit = true;
      }
    }

    // DOT effect colors
    const DOT_COLORS = {
      burn: '#ff4400',
      poison: '#88ff00',
      acid: '#00ff00',
      bleed: '#cc0000'
    };

    // Enemy attacks and DOT damage
    for (const enemy of enemies) {
      // Per-frame target override for charm and noise-maker
      if (enemy.isCharmed && enemy.isCharmed()) {
        // Charmed: fight nearest non-charmed enemy
        let nearestEnemy = null;
        let nearestDist = Infinity;
        for (const other of enemies) {
          if (other === enemy || (other.isCharmed && other.isCharmed())) continue;
          const dx = other.position.x - enemy.position.x;
          const dy = other.position.y - enemy.position.y;
          const d = Math.sqrt(dx * dx + dy * dy);
          if (d < nearestDist) {
            nearestDist = d;
            nearestEnemy = other;
          }
        }
        enemy.setTarget(nearestEnemy ?? player);
      } else {
        // Restore target to player when charm expires
        if (enemy.target !== player) {
          enemy.setTarget(player);
        }
        // Noise-maker redirect: pull enemy toward noise source instead of player
        if (noiseSource) {
          const dx = noiseSource.x - enemy.position.x;
          const dy = noiseSource.y - enemy.position.y;
          if (Math.sqrt(dx * dx + dy * dy) <= noiseSource.radius) {
            enemy.lastKnownPosition = { x: noiseSource.x, y: noiseSource.y };
            enemy.aggroMemoryActive = true;
            enemy.setTarget(player); // keep formal target as player, memory pulls to noise
          }
        }
      }

      const updateResult = enemy.update(deltaTime);

      // Create damage numbers for DOT damage
      if (updateResult && updateResult.dotDamage) {
        for (const dotEvent of updateResult.dotDamage) {
          const color = DOT_COLORS[dotEvent.effect] || '#ffffff';
          this.createDamageNumber(dotEvent.damage, enemy.position.x, enemy.position.y, color);
        }
      }

      // Handle sap damage
      if (updateResult && updateResult.sapDamage) {
        const sapData = updateResult.sapDamage;
        const damageSource = {
          isBullet: false,
          element: null,
          attacker: enemy
        };
        const result = player.takeDamage(sapData.damage, damageSource);

        if (result.dodged) {
          this.createDamageNumber('DODGE', player.position.x, player.position.y, '#ffff00');
        } else if (result.blocked) {
          this.createDamageNumber('BLOCK', player.position.x, player.position.y, '#aaaaaa');
        } else if (result !== false) {
          this.createDamageNumber(sapData.damage, player.position.x, player.position.y, '#cc0000');

          // Handle reflection
          if (result.reflect && result.attacker) {
            result.attacker.takeDamage(result.reflect);
            this.createDamageNumber(result.reflect, result.attacker.position.x, result.attacker.position.y, '#ff8800');
          }
        }

        if (result === true) {
          return { playerDead: true };
        }
      }

      // Handle melee attack windup visualization
      if (enemy.attackType === 'melee' && enemy.isWindingUp && enemy.isWindingUp()) {
        // Enemy is winding up a melee attack - create/update windup visual
        if (!enemy.windupAttackVisual) {
          const windupVisual = enemy.createWindupAttackVisual();
          if (windupVisual) {
            this.enemyMeleeAttacks.push(windupVisual);
            enemy.windupAttackVisual = windupVisual; // Track on enemy
          }
        }
      } else if (enemy.windupAttackVisual) {
        // Windup ended - convert visual to real attack or remove it
        if (enemy.canAttack()) {
          // Activate the attack (make it deal damage and flash white)
          enemy.windupAttackVisual.windupPhase = false;
          enemy.windupAttackVisual.hasHit = false; // Allow damage
          enemy.windupAttackVisual.flashWhite = true; // Flash white on activation
          enemy.windupAttackVisual.flashTimer = 0.1; // Flash for 0.1 seconds
          enemy.windupAttackVisual.duration = 0.15; // Reset to normal attack duration
          enemy.windupAttackVisual.alpha = 1.0; // Ensure fully visible when activated

          // Set attack cooldown (same as createAttack does)
          enemy.attackTimer = enemy.attackCooldown;
          enemy.state = 'idle';
        } else {
          // Windup was interrupted - remove the visual
          const index = this.enemyMeleeAttacks.indexOf(enemy.windupAttackVisual);
          if (index > -1) {
            this.enemyMeleeAttacks.splice(index, 1);
          }
        }
        enemy.windupAttackVisual = null;
      }

      if (enemy.canAttack() && !enemy.windupAttackVisual) {
        const attackData = enemy.createAttack();
        if (attackData) {
          this.createEnemyAttack(attackData);
        }
      }
    }

    // Update stuck arrows (follow their targets and emit fire particles if burning)
    for (let i = this.stuckArrows.length - 1; i >= 0; i--) {
      const arrow = this.stuckArrows[i];

      // If stuck to something, check if target is dead and remove arrow
      if (arrow.stuckTo) {
        const targetDead = (arrow.stuckTo.hp !== undefined && arrow.stuckTo.hp <= 0) ||
                          arrow.stuckTo.destroyed;
        if (targetDead) {
          this.stuckArrows.splice(i, 1);
          continue;
        }

        // Update position to follow target
        arrow.position.x = arrow.stuckTo.position.x + arrow.offset.x;
        arrow.position.y = arrow.stuckTo.position.y + arrow.offset.y;
      }
      // If on ground (stuckTo === null), arrow stays at fixed position

      // Fire arrows emit flame particles
      if (arrow.isBurning) {
        arrow.burnParticleTimer -= deltaTime;
        if (arrow.burnParticleTimer <= 0) {
          // Emit a small flame particle
          const angle = Math.random() * Math.PI * 2;
          const speed = 10 + Math.random() * 20;
          this.impactEffects.push({
            x: arrow.position.x,
            y: arrow.position.y,
            onHit: 'burn',
            color: arrow.color
          });
          arrow.burnParticleTimer = 0.1; // Emit every 0.1 seconds
        }
      }
    }

    const objectEffects = this.objectDestroyEvents.splice(0);
    const impactEffects = this.impactEffects.splice(0);
    const newSteamClouds = this.newSteamClouds.splice(0);
    const polymorphEvents = this.polymorphEvents.splice(0);
    return { playerDead: false, objectEffects, impactEffects, newSteamClouds, polymorphEvents };
  }

  createAttack(attackData, enemies = []) {
    if (!attackData) return;

    if (Array.isArray(attackData)) {
      // Multiple projectiles
      for (const data of attackData) {
        this.addAttack(data, enemies);
      }
    } else {
      return this.addAttack(attackData, enemies);
    }
  }

  addAttack(attackData, enemies = []) {
    if (attackData.type === 'bullet' || attackData.type === 'arrow' || attackData.type === 'transmutation_bolt') {
      this.projectiles.push({
        ...attackData,
        width: GRID.CELL_SIZE,
        height: GRID.CELL_SIZE,
        plane: attackData.shooterPlane !== undefined ? attackData.shooterPlane : 0 // Inherit plane from shooter
      });
    } else if (attackData.type === 'melee') {
      // Check if this is a delayed attack (for sequential animations like flail sweep)
      if (attackData.delay && attackData.delay > 0) {
        this.pendingMeleeAttacks.push({
          ...attackData
        });
      } else {
        this.meleeAttacks.push({
          ...attackData,
          hasHit: false
        });
      }
    } else if (attackData.type === 'chaos_wand' || attackData.type === 'blind_wand') {
      // Wand attacks with proximity requirement
      // Check if at least one enemy is within proximity range
      const hasNearbyEnemy = this.checkProximity(attackData.position, attackData.proximityRequired, enemies);

      if (!hasNearbyEnemy) {
        // Proximity requirement not met - show red X feedback and don't consume attack
        // Store failed attempt for visual feedback (blinking circle showing requirement radius)
        this.wandProximityFailures = this.wandProximityFailures || [];
        this.wandProximityFailures.push({
          position: attackData.position,
          proximityRequired: attackData.proximityRequired,
          timer: 0.5, // Show for 0.5 seconds
          color: '#ff0000'
        });
        return false; // Indicate failure
      }

      // Proximity met - process wand attack
      if (attackData.type === 'chaos_wand') {
        // Create AOE explosion centered on player
        this.createExplosion(
          attackData.position.x,
          attackData.position.y,
          attackData.blastRadius,
          attackData.damage,
          enemies,
          [],
          attackData.damageMin // Pass damage falloff
        );
        // Add visual AOE effect
        this.aoeEffects.push({
          type: 'chaos',
          x: attackData.position.x,
          y: attackData.position.y,
          radius: attackData.blastRadius,
          timer: 0.3, // Show for 0.3 seconds
          color: attackData.color || '#9932cc'
        });
      } else if (attackData.type === 'blind_wand') {
        // Apply blind status to all enemies in radius
        const affectedCount = this.applyAOEStatus(
          attackData.position,
          attackData.effectRadius,
          'blind',
          attackData.effectDuration,
          enemies
        );
        // Add visual AOE effect
        this.aoeEffects.push({
          type: 'blind',
          x: attackData.position.x,
          y: attackData.position.y,
          radius: attackData.effectRadius,
          timer: 0.3, // Show for 0.3 seconds
          color: attackData.color || '#444444'
        });
      }

      return true; // Indicate success
    }
  }

  checkProjectileCollision(proj, enemy) {
    const projBox = {
      x: proj.position.x,
      y: proj.position.y,
      width: proj.width || GRID.CELL_SIZE,
      height: proj.height || GRID.CELL_SIZE
    };

    const enemyBox = enemy.getHitbox();

    return projBox.x < enemyBox.x + enemyBox.width &&
           projBox.x + projBox.width > enemyBox.x &&
           projBox.y < enemyBox.y + enemyBox.height &&
           projBox.y + projBox.height > enemyBox.y;
  }

  checkMeleeCollision(attack, enemy) {
    // Use more precise hitbox matching character size (not full tile)
    // Characters are ~50% of tile width, ~75% of tile height
    const widthReduction = attack.width * 0.5;
    const heightReduction = attack.height * 0.25;
    const attackBox = {
      x: attack.position.x + widthReduction / 2,
      y: attack.position.y + heightReduction / 2,
      width: attack.width - widthReduction,
      height: attack.height - heightReduction
    };

    const enemyBox = enemy.getHitbox();

    return attackBox.x < enemyBox.x + enemyBox.width &&
           attackBox.x + attackBox.width > enemyBox.x &&
           attackBox.y < enemyBox.y + enemyBox.height &&
           attackBox.y + attackBox.height > enemyBox.y;
  }

  checkMeleeCollisionWithObject(attack, obj) {
    // Use more precise hitbox matching character size (not full tile)
    const widthReduction = attack.width * 0.5;
    const heightReduction = attack.height * 0.25;
    const attackBox = {
      x: attack.position.x + widthReduction / 2,
      y: attack.position.y + heightReduction / 2,
      width: attack.width - widthReduction,
      height: attack.height - heightReduction
    };

    const objBox = obj.getHitbox();

    return attackBox.x < objBox.x + objBox.width &&
           attackBox.x + attackBox.width > objBox.x &&
           attackBox.y < objBox.y + objBox.height &&
           attackBox.y + attackBox.height > objBox.y;
  }

  checkRicochet(proj) {
    let bounced = false;

    if (proj.position.x < 0) {
      proj.position.x = 0;
      proj.velocity.vx = Math.abs(proj.velocity.vx);
      bounced = true;
    } else if (proj.position.x > GRID.WIDTH) {
      proj.position.x = GRID.WIDTH;
      proj.velocity.vx = -Math.abs(proj.velocity.vx);
      bounced = true;
    }

    if (proj.position.y < 0) {
      proj.position.y = 0;
      proj.velocity.vy = Math.abs(proj.velocity.vy);
      bounced = true;
    } else if (proj.position.y > GRID.HEIGHT) {
      proj.position.y = GRID.HEIGHT;
      proj.velocity.vy = -Math.abs(proj.velocity.vy);
      bounced = true;
    }

    return bounced;
  }

  isOutOfBounds(proj) {
    return proj.position.x < 0 ||
           proj.position.y < 0 ||
           proj.position.x > GRID.WIDTH ||
           proj.position.y > GRID.HEIGHT;
  }

  createEnemyAttack(attackData) {
    if (!attackData) return;

    if (Array.isArray(attackData)) {
      // Multiple projectiles (magic, fire breath, etc)
      for (const data of attackData) {
        this.enemyProjectiles.push({
          ...data,
          width: GRID.CELL_SIZE,
          height: GRID.CELL_SIZE,
          plane: data.shooterPlane !== undefined ? data.shooterPlane : 0 // Inherit plane from shooter
        });
      }
    } else if (attackData.type === 'enemy_melee') {
      // Melee attack
      this.enemyMeleeAttacks.push({
        ...attackData,
        hasHit: false
      });
    } else {
      // Single projectile
      this.enemyProjectiles.push({
        ...attackData,
        width: GRID.CELL_SIZE,
        height: GRID.CELL_SIZE,
        plane: attackData.shooterPlane !== undefined ? attackData.shooterPlane : 0 // Inherit plane from shooter
      });
    }
  }

  checkProjectileCollisionWithPlayer(proj, player) {
    const projBox = {
      x: proj.position.x,
      y: proj.position.y,
      width: proj.width || GRID.CELL_SIZE,
      height: proj.height || GRID.CELL_SIZE
    };

    const playerBox = player.getHitbox();

    return projBox.x < playerBox.x + playerBox.width &&
           projBox.x + projBox.width > playerBox.x &&
           projBox.y < playerBox.y + playerBox.height &&
           projBox.y + projBox.height > playerBox.y;
  }

  checkMeleeCollisionWithPlayer(attack, player) {
    // Use more precise hitbox matching character size (not full tile)
    const widthReduction = attack.width * 0.5;
    const heightReduction = attack.height * 0.25;
    const attackBox = {
      x: attack.position.x + widthReduction / 2,
      y: attack.position.y + heightReduction / 2,
      width: attack.width - widthReduction,
      height: attack.height - heightReduction
    };

    const playerBox = player.getHitbox();

    return attackBox.x < playerBox.x + playerBox.width &&
           attackBox.x + attackBox.width > playerBox.x &&
           attackBox.y < playerBox.y + playerBox.height &&
           attackBox.y + attackBox.height > playerBox.y;
  }

  updateRollDamage(player, enemies, backgroundObjects) {
    if (!player || player.dodgeRoll.type !== 'damage') return;

    const rolling = player.dodgeRoll.active;

    // Reset hit-tracking sets at the start of each new roll
    if (rolling && !this._rollWasActive) {
      this._rollHitEnemies = new Set();
      this._rollHitObjects = new Set();
    }
    this._rollWasActive = rolling;

    if (!rolling) return;

    const hitbox = { x: player.position.x, y: player.position.y, width: player.width, height: player.height };
    const dir = player.dodgeRoll.direction;

    // Damage enemies on contact (once per enemy per roll)
    for (const enemy of enemies) {
      if (this._rollHitEnemies.has(enemy) || enemy.hp <= 0) continue;
      const eb = enemy.getHitbox();
      if (hitbox.x < eb.x + eb.width && hitbox.x + hitbox.width > eb.x &&
          hitbox.y < eb.y + eb.height && hitbox.y + hitbox.height > eb.y) {
        this._rollHitEnemies.add(enemy);
        enemy.takeDamage(1);
        this.createDamageNumber(1, enemy.position.x, enemy.position.y, '#ff4444');
        // Knockback in the roll direction
        enemy.velocity.vx = dir.x * 300;
        enemy.velocity.vy = dir.y * 300;
        if (enemy.applyStatusEffect) enemy.applyStatusEffect('knockback', 0.25);
      }
    }

    // Smash background objects on contact (once per object per roll)
    for (const obj of backgroundObjects) {
      if (obj.destroyed || obj.isRecipeSign || obj.indestructible || obj.hp === null) continue;
      if (this._rollHitObjects.has(obj)) continue;
      const ob = obj.getHitbox();
      if (hitbox.x < ob.x + ob.width && hitbox.x + hitbox.width > ob.x &&
          hitbox.y < ob.y + ob.height && hitbox.y + hitbox.height > ob.y) {
        this._rollHitObjects.add(obj);
        const result = obj.takeDamage(1, false);
        if (result.destroyed && result.effect) {
          this.objectDestroyEvents.push({ obj, effect: result.effect });
        }
      }
    }
  }

  applyKnockback(enemy, attack) {
    const dx = enemy.position.x - attack.position.x;
    const dy = enemy.position.y - attack.position.y;
    const distance = Math.sqrt(dx * dx + dy * dy) || 1;

    const knockbackForce = attack.knockback || 200;
    enemy.velocity.vx = (dx / distance) * knockbackForce;
    enemy.velocity.vy = (dy / distance) * knockbackForce;

    // Activate knockback status effect to prevent AI from overriding velocity
    if (enemy.applyStatusEffect) {
      enemy.applyStatusEffect('knockback', 0.2); // 0.2 second knockback duration
    }
  }

  /**
   * Update projectile's plane based on tunnel boundaries
   * Projectiles switch planes when crossing tunnel boundaries from the correct axis
   */
  updateProjectilePlane(projectile, tunnelData) {
    const { bounds, entranceAxis } = tunnelData;

    // Convert projectile position to grid coordinates
    const projGridX = Math.floor(projectile.position.x / GRID.CELL_SIZE);
    const projGridY = Math.floor(projectile.position.y / GRID.CELL_SIZE);

    // Check if projectile is inside tunnel bounds
    const inTunnelBounds =
      projGridX >= bounds.minCol && projGridX <= bounds.maxCol &&
      projGridY >= bounds.minRow && projGridY <= bounds.maxRow;

    // Determine target plane based on position
    const targetPlane = inTunnelBounds ? 1 : 0;

    // Only switch planes if entering from the correct axis
    if (targetPlane !== projectile.plane) {
      const crossingFromCorrectAxis = this.checkProjectileTunnelEntrance(projectile, bounds, entranceAxis);

      if (crossingFromCorrectAxis) {
        projectile.plane = targetPlane;
      }
    }
  }

  /**
   * Check if projectile is entering tunnel from the correct axis
   * For horizontal tunnels: must enter from left/right edges
   * For vertical tunnels: must enter from top/bottom edges
   */
  checkProjectileTunnelEntrance(projectile, bounds, entranceAxis) {
    const projGridX = Math.floor(projectile.position.x / GRID.CELL_SIZE);
    const projGridY = Math.floor(projectile.position.y / GRID.CELL_SIZE);

    if (entranceAxis === 'horizontal') {
      // Horizontal tunnel: check if entering from left or right edge
      const atLeftEdge = projGridX === bounds.minCol;
      const atRightEdge = projGridX === bounds.maxCol;
      const withinVerticalBounds = projGridY >= bounds.minRow && projGridY <= bounds.maxRow;

      return (atLeftEdge || atRightEdge) && withinVerticalBounds;
    } else {
      // Vertical tunnel: check if entering from top or bottom edge
      const atTopEdge = projGridY === bounds.minRow;
      const atBottomEdge = projGridY === bounds.maxRow;
      const withinHorizontalBounds = projGridX >= bounds.minCol && projGridX <= bounds.maxCol;

      return (atTopEdge || atBottomEdge) && withinHorizontalBounds;
    }
  }

  createChainLightning(source, hitEnemy, enemies) {
    const chainRange = 80;
    const chainDamage = source.damage * 0.5;
    const maxChains = source.chainCount || 3;

    let chained = 0;
    const alreadyHit = new Set([hitEnemy]);

    let currentEnemy = hitEnemy;
    while (chained < maxChains) {
      let nearestEnemy = null;
      let nearestDist = Infinity;

      for (const enemy of enemies) {
        if (alreadyHit.has(enemy)) continue;

        const dx = enemy.position.x - currentEnemy.position.x;
        const dy = enemy.position.y - currentEnemy.position.y;
        const dist = Math.sqrt(dx * dx + dy * dy);

        if (dist < chainRange && dist < nearestDist) {
          nearestEnemy = enemy;
          nearestDist = dist;
        }
      }

      if (!nearestEnemy) break;

      const isWet = nearestEnemy.isWet && nearestEnemy.isWet();
      const actualDamage = isWet ? chainDamage * 2 : chainDamage;
      const stunDur = isWet ? 3.5 : 2.0;

      nearestEnemy.takeDamage(actualDamage);
      nearestEnemy.applyStatusEffect('stun', stunDur);
      this.createDamageNumber(actualDamage, nearestEnemy.position.x, nearestEnemy.position.y, '#00ffff');
      if (isWet) {
        this.createDamageNumber('⚡', nearestEnemy.position.x, nearestEnemy.position.y - 12, '#ffff00');
      }
      alreadyHit.add(nearestEnemy);
      currentEnemy = nearestEnemy;
      chained++;
    }
  }

  // Check if at least one enemy is within proximity range
  // position: player's center position
  checkProximity(position, proximityRange, enemies) {
    for (const enemy of enemies) {
      // Calculate enemy center position (enemy.position is top-left)
      const enemyCenterX = enemy.position.x + (enemy.width || GRID.CELL_SIZE) / 2;
      const enemyCenterY = enemy.position.y + (enemy.height || GRID.CELL_SIZE) / 2;

      const dx = enemyCenterX - position.x;
      const dy = enemyCenterY - position.y;
      const dist = Math.sqrt(dx * dx + dy * dy);

      if (dist <= proximityRange) {
        return true; // At least one enemy in range
      }
    }
    return false; // No enemies in range
  }

  // Apply status effect to all enemies in radius
  applyAOEStatus(position, radius, statusType, duration, enemies) {
    let affectedCount = 0;
    for (const enemy of enemies) {
      const dx = enemy.position.x - position.x;
      const dy = enemy.position.y - position.y;
      const dist = Math.sqrt(dx * dx + dy * dy);

      if (dist <= radius) {
        enemy.applyStatusEffect(statusType, duration);
        affectedCount++;
      }
    }
    return affectedCount;
  }

  createExplosion(x, y, radius, damage, enemies, backgroundObjects = [], damageMin = 0) {
    // Damage enemies in blast radius
    // damageMin: minimum damage multiplier at edge (0 = full falloff, 0.25 = 25% damage at edge)
    for (const enemy of enemies) {
      const dx = enemy.position.x - x;
      const dy = enemy.position.y - y;
      const dist = Math.sqrt(dx * dx + dy * dy);

      if (dist <= radius) {
        // Calculate damage falloff: ranges from 1.0 at center to damageMin at edge
        const falloffRange = 1.0 - damageMin;
        const damageFalloff = damageMin + falloffRange * (1 - dist / radius);
        const explosionDamage = Math.ceil(damage * damageFalloff);

        enemy.takeDamage(explosionDamage);
        this.createDamageNumber(explosionDamage, enemy.position.x, enemy.position.y, '#ff8800');

        // Knockback from explosion center
        if (dist > 0) {
          const knockbackForce = 300 * damageFalloff;
          enemy.velocity.vx = (dx / dist) * knockbackForce;
          enemy.velocity.vy = (dy / dist) * knockbackForce;
        }
      }
    }

    // Affect background objects in blast radius
    for (const obj of backgroundObjects) {
      if (obj.destroyed || obj.isRecipeSign) continue; // Skip destroyed and recipe signs

      const dx = obj.position.x - x;
      const dy = obj.position.y - y;
      const dist = Math.sqrt(dx * dx + dy * dy);

      if (dist <= radius) {
        // Glittering rocks: explosions always destroy and drop gems
        if (obj.data?.glitteringRock) {
          const result = obj.takeDamage(9999);
          if (result.destroyed && result.effect) {
            this.objectDestroyEvents.push({ obj, effect: result.effect });
          }
          continue;
        }

        const damageFalloff = 1 - (dist / radius);
        const explosionDamage = Math.ceil(damage * damageFalloff);

        // Ignite flammable objects
        if (obj.isFlammable && obj.isFlammable()) {
          obj.ignite(5.0);
        }

        // Damage destructible objects
        if (!obj.indestructible && obj.hp !== null) {
          const result = obj.takeDamage(explosionDamage);
          if (result.destroyed && result.effect) {
            this.objectDestroyEvents.push({ obj, effect: result.effect });
          }
        }
      }
    }

    // Create visual effect (you can enhance this later)
    this.createDamageNumber('BOOM!', x, y, '#ff4400');
  }

  createSplitProjectiles(originalProj) {
    const splitCount = originalProj.splitCount || 3;
    const angle = Math.atan2(originalProj.velocity.vy, originalProj.velocity.vx);
    const speed = Math.sqrt(originalProj.velocity.vx ** 2 + originalProj.velocity.vy ** 2);

    for (let i = 0; i < splitCount; i++) {
      const spreadAngle = angle + (i - Math.floor(splitCount / 2)) * 0.4;

      this.projectiles.push({
        type: originalProj.type,
        char: originalProj.char,
        position: { ...originalProj.position },
        velocity: {
          vx: Math.cos(spreadAngle) * speed * 0.8,
          vy: Math.sin(spreadAngle) * speed * 0.8
        },
        damage: Math.ceil(originalProj.damage * 0.6),
        color: originalProj.color,
        width: GRID.CELL_SIZE,
        height: GRID.CELL_SIZE,
        hasSplit: true // Prevent infinite splitting
      });
    }
  }

  createDamageNumber(damage, x, y, color, scale = 1) {
    this.damageNumbers.push({
      value: damage,
      x: x + GRID.CELL_SIZE / 2,
      y: y,
      alpha: 1.0,
      timer: 0,
      duration: 1.0,  // 1 second lifetime
      riseSpeed: 30,  // pixels per second
      color: color,
      scale: scale
    });
  }

  clear() {
    this.projectiles = [];
    this.enemyProjectiles = [];
    this.meleeAttacks = [];
    this.enemyMeleeAttacks = [];
    this.pendingMeleeAttacks = [];
    this.damageNumbers = [];
    this.stuckArrows = [];
  }

  getProjectiles() {
    return this.projectiles;
  }

  getEnemyProjectiles() {
    return this.enemyProjectiles;
  }

  getMeleeAttacks() {
    return this.meleeAttacks;
  }

  getEnemyMeleeAttacks() {
    return this.enemyMeleeAttacks;
  }

  getDamageNumbers() {
    return this.damageNumbers;
  }

  getStuckArrows() {
    return this.stuckArrows;
  }

  checkProjectileCollisionWithObject(proj, obj) {
    const projBox = {
      x: proj.position.x,
      y: proj.position.y,
      width: proj.width || GRID.CELL_SIZE,
      height: proj.height || GRID.CELL_SIZE
    };

    const objBox = obj.getHitbox();

    return projBox.x < objBox.x + objBox.width &&
           projBox.x + projBox.width > objBox.x &&
           projBox.y < objBox.y + objBox.height &&
           projBox.y + projBox.height > objBox.y;
  }

  reflectBullet(bullet, obj) {
    // Calculate reflection angle with some randomness
    const angle = Math.atan2(bullet.velocity.vy, bullet.velocity.vx);
    const reflectedAngle = angle + Math.PI + (Math.random() - 0.5) * 1.0;

    const speed = Math.sqrt(bullet.velocity.vx ** 2 + bullet.velocity.vy ** 2);
    bullet.velocity.vx = Math.cos(reflectedAngle) * speed;
    bullet.velocity.vy = Math.sin(reflectedAngle) * speed;

    // Mark as reflected so it doesn't hit player
    bullet.reflected = true;

    // Create sparkle effect (TODO: add to particle system)
    this.createDamageNumber('✧', obj.position.x, obj.position.y, '#ffff00');
  }

  conductElectricity(sourceObj, damage, enemies, player = null) {
    const BASE_RANGE = 48;
    const WET_RANGE = 80;
    const WET_MULT = 2.0;

    for (const enemy of enemies) {
      if (!enemy.isWet || !enemy.isWet()) continue;

      const dx = enemy.position.x - sourceObj.position.x;
      const dy = enemy.position.y - sourceObj.position.y;
      const dist = Math.sqrt(dx * dx + dy * dy);

      if (dist <= WET_RANGE) {
        const dmg = Math.ceil(damage * WET_MULT);
        enemy.takeDamage(dmg);
        enemy.applyStatusEffect('stun', 3.5);
        this.createDamageNumber(dmg, enemy.position.x, enemy.position.y, '#00ffff');
        this.createDamageNumber('⚡', enemy.position.x, enemy.position.y - 10, '#ffff00');
      }
    }

    // Also damage wet player (they're in the electrical field)
    if (player && player.isWet && player.isWet()) {
      const dx = player.position.x - sourceObj.position.x;
      const dy = player.position.y - sourceObj.position.y;
      if (Math.sqrt(dx * dx + dy * dy) <= WET_RANGE) {
        const dead = player.takeDamage(Math.ceil(damage * WET_MULT));
        if (dead === true) {
          this.createDamageNumber(Math.ceil(damage * WET_MULT), player.position.x, player.position.y, player.color);
          return { playerDead: true };
        }
      }
    }

    return null;
  }
}
